### ISSUE TITLE
Delete old project button

### ISSUE THREAD

**Issue by pmaus** [sig-gis/mapcha#15]
We need to be able to delete old projects. We've been doing a lot of testing and would like to clean up the directories. This should be a top secret admin. only function.

**Comment by lambdatronic** [comment]
Hi Paul,

  That's already on the Admin page. Just select an old project from the
dropdown menu, and the "Create and launch this project" button will
change its text to "Delete this project". You can push that button to
delete old projects.

This feature has been in the site for the past two days. I just haven't
enabled the Delete button yet, so it just pops up a message saying that
the delete feature hasn't yet been implemented. I wanted to make sure
David and I had a clear plan on how to archive old projects in case they
need to be reinstated in the future. Since then, we chatted and I know
how we're going to do it now. I just need to write a bit of code to
implement it.

Cheers,
  Gary

**Comment by lambdatronic** [comment]
Okay. The Delete Project button now works correctly on the Admin page. Have fun!

**Comment by pmaus** [comment]
Great - thanks. We'll be doing some more set test today so I'll use that.

Paul
